<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <RepositoryUrl>https://github.com/brianberns/AlgEff</RepositoryUrl>
    <PackageProjectUrl>https://github.com/brianberns/AlgEff</PackageProjectUrl>
    <PackageIcon></PackageIcon>
    <Authors>Brian Berns</Authors>
    <Company>Bernsrite Industries</Company>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestEnvironments.fs" />
    <Compile Include="EffectCETest.fs" />
    <Compile Include="ErrorTest.fs" />
    <Compile Include="GreetTest.fs" />
    <Compile Include="StateTest.fs" />
    <Compile Include="NonDetTest.fs" />
    <Compile Include="AsyncTest.fs" />
    <Compile Include="ActualConsoleTest.fs" />
    <Compile Include="CombineTest.fs" />
    <Compile Include="ConcurrencyTest.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgEff\AlgEff.fsproj" />
  </ItemGroup>

</Project>
